### ISSUE TITLE
Hi! It would be better to replace FFDFDFDF to FFABB2BF, thank you!

### ISSUE THREAD

**Issue by szzhiyang** [AdrianWilczynski/OneDarkPro#1]

**Comment by AdrianWilczynski** [comment]
Yeah, you're right. It seems to be the color that VSCode theme uses for plain text and it does look better. Thanks for catching this. I'll change it soon.

**Comment by szzhiyang** [comment]
@AdrianWilczynski Thank you very much! I can't use Visual Studio without your masterpiece now! 😄

**Comment by AdrianWilczynski** [comment]
I've pushed the update. You should be able to download it now. Thanks again for the report.

**Comment by szzhiyang** [comment]
@AdrianWilczynski You're welcome. 😄 The update is perfect! 👍  Your masterpiece makes me fall in love with Visual Studio again! ❤️
