### ISSUE TITLE
Create a new branch dialog

### ISSUE THREAD

**Issue by ryanbuening** [AdrianWilczynski/OneDarkPro#13]
The "Create a new branch" dialog looks like the following:

![image](https://user-images.githubusercontent.com/812974/102107810-2533b580-3e00-11eb-835b-a5f93ccf2914.png)

Not sure if this is "themeable" or not? When using the default Dark theme it looks like the following:

![image](https://user-images.githubusercontent.com/812974/102108293-bc990880-3e00-11eb-88de-ed26c9d64c4c.png)

**Comment by AdrianWilczynski** [comment]
Thanks for the report. I'll try to look into this soon.

**Comment by AdrianWilczynski** [comment]
Partially fixed 😅 I've changed the background, but there is still an issue with the "checkout branch" checkbox not being visible. I'll try to look into this again later.

**Comment by luhansen-ms** [comment]
@AdrianWilczynski FYI this issue popped up again https://developercommunity.visualstudio.com/t/Bug-on-Git-checkout-Git-checkout-window/10122911#T-ND10132051

We're using the color keys from `ThemedUtilityDialogColors.Window*ColorKey` for a many other dialogs as well :)

Cheers,
Luke

**Comment by coosfix** [comment]
![image](https://user-images.githubusercontent.com/45789268/198462276-d236438d-1da0-4b65-91e2-5cf60f2747cf.png)
hava same problem :(  
any one fix this ?

**Comment by AdrianWilczynski** [comment]
Fixed in https://github.com/AdrianWilczynski/OneDarkPro/commit/b430e352d153d0e04d2a3533ea3c2a53d1e728d1.
Thanks @luhansen-ms!
