### ISSUE TITLE
Remove text background on razor files

### ISSUE THREAD

**Issue by SLMNBJ** [AdrianWilczynski/OneDarkPro#15]
What color should I set to remove the background?

**Comment by AdrianWilczynski** [comment]
Some guy left a comment here talking about the same thing - https://marketplace.visualstudio.com/items?itemName=adrianwilczynski.one-dark-pro&ssr=false#review-details (first one). Does that work for you?

**Comment by SLMNBJ** [comment]
@AdrianWilczynski setting HTML Razor Code Background to Automatic works perfectly.
Nice Theme!
