### ISSUE TITLE
Add to 64 bit Visual Studio 2022 marketplace

### ISSUE THREAD

**Issue by devgid** [AdrianWilczynski/OneDarkPro#17]
Migration: https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022

**Comment by sheharyarshahid** [comment]
I was also waiting for this to be supported for VS 2022. The only dark theme I actually like and use daily 😍

**Comment by MrCSharp22** [comment]
Made a PR to add support for VS 2022: https://github.com/AdrianWilczynski/OneDarkPro/pull/18 
Hopefully this can be merged and published soon.

If you checkout that branch and build, you will find a vsix package in the bin folder which you can use to install this on the 2022 preview instance.

**Comment by ryanbuening** [comment]
Attached is the VSIX from @MrCSharp22's PR:
[OneDarkPro VS 2022.zip](https://github.com/AdrianWilczynski/OneDarkPro/files/6755271/OneDarkPro.VS.2022.zip)
