### ISSUE TITLE
Color issues for html attribute name and razor component in VS 2022

### ISSUE THREAD

**Issue by TanvirArjel** [AdrianWilczynski/OneDarkPro#24]
For HTML attribute name, the current color is pure red which seems odd and feels like error as follows:

![InkedCapture_LI](https://user-images.githubusercontent.com/14342773/134563450-e7b3ca44-3d54-46af-b81b-2a5119e46315.jpg)

**Suggestion: You can choose `Magenta` for the HTML attribute name and it will shows as follows:**

![image](https://user-images.githubusercontent.com/14342773/134563582-1d65b834-f83c-431f-a09c-1c52b5c99afc.png)

Now the current color (Purple) for the razor component is almost unreadable as follows:

![Inkedrazor_LI](https://user-images.githubusercontent.com/14342773/134566492-f13b3cea-9bc0-44b6-b839-3af3c9d1e8f3.jpg)

**Suggestion: Please choose the following color for razor component**

1. Razor Component Element - Olive
2. Razor Component Attribute-  Magenta
3. Razor Tag Helper Element - Olive
4.  Razor Tag Helper Attribute - Magenta
5. Razor Directive (foreground) - Yellow
6. Razor Directive (background) - Automatic (Background of the text editor)

Then it will look like as follows:

![image](https://user-images.githubusercontent.com/14342773/134565603-16ed6fa9-3121-4bbb-b8b9-91bd518831a1.png)

![image](https://user-images.githubusercontent.com/14342773/134565667-f3a8a81e-81bb-41c4-b9bf-eeaa284d8d69.png)

**Comment by AdrianWilczynski** [comment]
Hi, thanks for the report. Something must have changed between Visual Studio 2019 and 2022 because it shouldn't look like that.

I don't know if it's going to be easy to fix because Visual Studio Color Theme Designer isn't yet supported on Visual Studio 2022.

![image](https://user-images.githubusercontent.com/31390726/134570057-00862787-a0eb-467a-8bb5-1cc3c446a2b6.png)

**Comment by TanvirArjel** [comment]
@AdrianWilczynski It looks like html attribute and razor component colors are fine in Visual Stuido 2019.

Hope you will find a way to fix this for Visual Studio 2022.

Thanks in advance.

**Comment by AdrianWilczynski** [comment]
It's not a fix, but it seems like you can override invalid default through settings. 

![image](https://user-images.githubusercontent.com/31390726/134582163-f372f82a-d46f-4e0c-b933-98046c187177.png)

**Comment by TanvirArjel** [comment]
I have already done this. 😀

**Comment by AdrianWilczynski** [comment]
Makes sense. It didn't click for me that you had to do something like that to make the screenshots 😅.

**Comment by TanvirArjel** [comment]
@AdrianWilczynski 

>Hi, thanks for the report. Something must have changed between Visual Studio 2019 and 2022 because it shouldn't look like that.

>I don't know if it's going to be easy to fix because Visual Studio Color Theme Designer isn't yet supported on Visual Studio 2022.

Did you try to reach out to the Visual Studio 2022 team by submitting an issue regarding the above things?

**Comment by jeffward01** [comment]
Does anyone else have this issue? I want to use this theme for my Blazor Development, but afraid of these color issues

**Comment by AdrianWilczynski** [comment]
Partially fixed by: https://github.com/AdrianWilczynski/OneDarkPro/commit/e0dd92c9595edaac682f0ffac91539f82e6c5209
