### ISSUE TITLE
Missing color for CodeLens window & pop up

### ISSUE THREAD

**Issue by stardust-36** [AdrianWilczynski/OneDarkPro#25]
Recently I noticed there are 2 buttons(Collapse All, Refresh) missing color in the Codelens window and pop up. Please see the red circles in the following screenshots.

Visual Studio 2022 17.0.1
OneDark Pro 1.2.0

![image](https://user-images.githubusercontent.com/5809129/143789211-15700856-d070-4204-a596-b5903e813c6f.png)
![image](https://user-images.githubusercontent.com/5809129/143789118-658039c8-30be-4306-92e8-baabb8b6ff3d.png)

**Comment by AdrianWilczynski** [comment]
Seems fine right now. 

Anyway, I think you could have been using this theme: https://marketplace.visualstudio.com/items?itemName=zhuangtongfa.onedarkpro. Attached screenshot looks more like it.
