### ISSUE TITLE
Menus always open to left side

### ISSUE THREAD

**Issue by zengouu** [AdrianWilczynski/OneDarkPro#26]
Using "right-click" menus inside C# editor always seem to open in the left side. See picture attached.

Versions used:

- VS 2022 17.0.5
- JetBrains ReSharper 2021.3.2

![image](https://user-images.githubusercontent.com/8158470/151319042-ab8f133e-014c-4821-921f-5ec6bcf93850.png)

**Comment by fgimian** [comment]
This doesn't happen for me personally.

**Comment by AdrianWilczynski** [comment]
I can't see how this theme could be causing this behavior. To my knowledge, it only edits colors.

It seems to be working fine on my end (but I don't use ReSharper).

Maybe you don't have enough screen space to the right?
