### ISSUE TITLE
When documents well is set to left, the background defaults to white

### ISSUE THREAD

**Issue by MrCSharp22** [AdrianWilczynski/OneDarkPro#3]
Hi,
When OneDarkPro theme is active and the document well is set to left (instead of the default top) the background is set to white when a document is active. 
However, when it loses focus (by clicking on another tool window) it goes back to a dark background:

![image](https://user-images.githubusercontent.com/8640943/81129341-5bb27380-8f87-11ea-903a-57f6448a693f.png)

I have cloned the repo and tried to find out which style is responsible for this but couldn't find it.

**Comment by AdrianWilczynski** [comment]
Hi, thanks for the report. It should be fixed now though I couldn't find property responsible for the black project name.

**Comment by MrCSharp22** [comment]
That is just me hiding the project name with Greenshot 😁
Thanks for fixing it. I'll check out the diff to see which property was responsible for this.

**Comment by AdrianWilczynski** [comment]
<img width="241" alt="Example" src="https://user-images.githubusercontent.com/31390726/81169034-6b868380-8f98-11ea-8e66-cfc55ce118d5.PNG">

This is the "black name" I'm talking about. I think it would look better in light grey or something but I don't know how to change it.

**Comment by MrCSharp22** [comment]
Oh... my bad 😂 completely miss understood you there.
