### ISSUE TITLE
Incomplete support for other extension windows

### ISSUE THREAD

**Issue by GvmiHasan** [AdrianWilczynski/OneDarkPro#6]
Hi
Thanks for theme, it seems having incomplete support for other extensions window such as resharper.
![Annotation 2020-05-13 193914](https://user-images.githubusercontent.com/57360271/81930838-5ba51a00-95fe-11ea-9a78-c2294093baf0.jpg)

**Comment by AdrianWilczynski** [comment]
Hi, thanks for the report.

Sadly I don't know which property controls the color of these elements or if there even is one. There doesn't seem to be Resharper specific property that could be responsible for this. I can't find it using color picker either.

I've tried some other dark themes (Night Owl, Solarized, Mid Century) and they all have the same issue.

So this will probably remain unfixed unless somebody can help me with it.
