### ISSUE TITLE
Track Changes after before save and after save are hard to identify

### ISSUE THREAD

**Issue by Wesley-Snipes** [AdrianWilczynski/OneDarkPro#7]
Color of Text Editor -> Track Changes before save and Text Editor -> Track Changes after save are similar to the background and hard to identify.

**Comment by AdrianWilczynski** [comment]
Hi, thanks for the report. Could you maybe include a screenshot? I'm not sure what I'm looking for.

**Comment by Wesley-Snipes** [comment]
[![2020-05-29-09-27-10-Accounting-Business-Running-Microsoft-Visual-Studio.png](https://i.postimg.cc/sXLKYJLh/2020-05-29-09-27-10-Accounting-Business-Running-Microsoft-Visual-Studio.png)](https://postimg.cc/47zzZpsf)

Thanks for the reply, in the pic I have modified the colors. The original colors are hard to identify.

**Comment by AdrianWilczynski** [comment]
Fixed 😄
